# Generated by Django 3.1.2 on 2020-10-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20201016_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.URLField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.kindpng.com%2Fimgv%2Fiwoxbb_user-profile-default-image-png-clipart-png-download%2F&psig=AOvVaw1nBZdT_xepbZ0omg9nW8Kl&ust=1602939157937000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCPCpyeqTuewCFQAAAAAdAAAAABAI'),
        ),
    ]
