# Generated by Django 3.1.2 on 2020-10-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20201016_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.URLField(default='https://www.kindpng.com/picc/b/24/248253.png'),
        ),
    ]
